Feature/auth/view - 2
Double-Slash/5th-final-team11 pull request #2
Opened 2020-12-05 11:35 UTC by junmin-Chang

2020-12-05 12:10 UTC, comforest requested changes

2020-12-05 12:10 UTC, comforest commented on Android/app/src/main/AndroidManifest.xml
> +        <activity android:name=".ui.LoginActivity">
ui.auth 같이 ui 패키지 아래는 기능으로 분리해주세요 ㅎㅎ

2020-12-05 12:10 UTC, comforest commented on Android/app/build.gradle
> +    implementation 'com.google.firebase:firebase-auth-ktx'
이 부분은 머지할때 체크하셔야 하는 부분입니다. 주석도 합치구요.
firebase-auth 와 firebase-auth-ktx 중 어느걸 사용하시면 좋을까요? ㅎㅎ

2020-12-05 12:10 UTC, comforest commented on Android/app/src/main/java/com/doubleslas/fifith/alcohol/ui/LoginActivity.kt
> +    private val GOOGLE_SIGN_IN = 1001
상수(const) 처리

2020-12-05 12:10 UTC, comforest commented on Android/app/src/main/java/com/doubleslas/fifith/alcohol/ui/LoginActivity.kt
> +    private var activityLoginBinding: ActivityLoginBinding? = null
Activity ViewBinding은 Nullable 하지 않게 공식 문서 예시에 잇더군요

2020-12-05 12:10 UTC, comforest commented on Android/app/src/main/java/com/doubleslas/fifith/alcohol/ui/LoginActivity.kt
> +    private var firebaseAuth: FirebaseAuth? = null
애도 가급적 NonNull 형태로

2020-12-05 12:10 UTC, comforest commented on Android/app/src/main/java/com/doubleslas/fifith/alcohol/ui/LoginActivity.kt
> +    private val authRepository by lazy { AuthRepository() }
View가 Model를 참조하지 않습니다. (아예 쓰면 안돼요)
ViewModel이 Model을 참조해야합니다
(아예 이 클래스에서 사용도 안하네요)

2020-12-05 12:10 UTC, comforest commented on Android/app/src/main/java/com/doubleslas/fifith/alcohol/ui/LoginActivity.kt
> +        activityLoginBinding = binding
```suggestion
        activityLoginBinding  = ActivityLoginBinding.inflate(layoutInflater)
```
이렇게 해도 되지 않을까요?

2020-12-05 12:10 UTC, comforest commented on Android/app/src/main/java/com/doubleslas/fifith/alcohol/ui/LoginViewModel.kt
> +                    Log.d("junmin", user.toString())
Login 이 끝나면 Model에 알려줘야합니다.

2020-12-05 12:10 UTC, comforest commented on Android/app/src/main/res/layout/activity_main.xml
> +<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
굳이 RelativeLayout 을 쓴 이유가 있나요?

2020-12-07 07:09 UTC, junmin-Chang commented on Android/app/build.gradle
> +    implementation 'com.google.firebase:firebase-auth-ktx'
ktx가 top level이라고 되어있어서 ktx만 적용해봤습니다

2020-12-07 07:34 UTC, comforest commented on Android/app/build.gradle
> +    implementation 'com.google.firebase:firebase-auth-ktx'
저는 ktx 가 Kotlin 버전으로 알고 있어요. 그래서 ktx 버전에서는
Firebase Auth를 받아오는 방법도 조금 바뀌었습니다

2020-12-07 07:46 UTC, comforest commented on Android/app/src/main/java/com/doubleslas/fifith/alcohol/ui/auth/LoginActivity.kt
>          firebaseAuth = FirebaseAuth.getInstance()
ktx 버전으로 바꾸면서 이 부분이 좀 변경 되었습니다

2020-12-09 05:17 UTC, comforest commented on Android/app/src/main/java/com/doubleslas/fifith/alcohol/ui/auth/LoginViewModel.kt
> +            }
Firebase Login 은 model에서 처리할게요.
View 에서 구글로그인을 하면
ViewModel에선 해당 데이터에서 FIrebase Credential을 추출해서 Repository에게 넘기기만 하면 됩니다.

2020-12-09 07:33 UTC, junmin-Chang commented on Android/app/src/main/java/com/doubleslas/fifith/alcohol/ui/auth/LoginViewModel.kt
> +            }
@comforest 음.. 어떻게 하는걸까요?

2020-12-09 07:36 UTC, comforest commented on Android/app/src/main/java/com/doubleslas/fifith/alcohol/ui/auth/LoginViewModel.kt
> +            }
@junmin-Chang 
```suggestion
        authRepository.completeLogin(credential)
```
이렇게요 ㅎㅎ...

2020-12-09 07:37 UTC, junmin-Chang commented on Android/app/src/main/java/com/doubleslas/fifith/alcohol/ui/auth/LoginViewModel.kt
> +            }
@comforest 아 삭제된 부분을 호연님께서 모델에서 처리하신다는 말씀이었나요?

2020-12-09 07:54 UTC, comforest commented on Android/app/src/main/java/com/doubleslas/fifith/alcohol/ui/auth/LoginViewModel.kt
> +            }
넵 ㅎㅎ 모델 코드 보시면 있을거에요

2020-12-21 03:20 UTC, comforest requested changes
또한 Firebase Auth 와 연동이 되어야 합니다.
물론이는 Model 부분에서 이루어져야 하구요

2020-12-21 03:20 UTC, comforest commented on Android/app/build.gradle
> +    annotationProcessor 'com.github.bumptech.glide:compiler:4.11.0'
Glide 가 먼지 아시나요?

2020-12-21 03:20 UTC, comforest commented on Android/app/src/main/java/com/doubleslas/fifith/alcohol/ui/auth/LoginActivity.kt
> +    private fun updateLoginInfo() {
보아하니 카카오 로그인 관련한 Update 메소드인 것 같은데
updateKakaoLoginInfo
와 같이 카카오 로그인과 관련되었다는 사실을 보여주셨으면 하네요

2020-12-21 05:54 UTC, junmin-Chang commented on Android/app/build.gradle
> +    annotationProcessor 'com.github.bumptech.glide:compiler:4.11.0'
@comforest  넵!

2020-12-30 05:24 UTC, closed without merging